<?php include 'include/header.php'; ?>
<div class="content-wrapper">
<div class="page-title">
<div class="container">
<h1 class="page-header zoomIn animated">Web Design and Development Terms and Conditions - Web Choice UK Ltd</h1>
<ol class="breadcrumb">
<li><a href="index.php">Home</a></li>
<li class="active">Web Design and Development Terms and Conditions - Web Choice UK Ltd</li>
</ol>
</div>
</div>
<div class="main-container container">
<header role="banner" id="page-header"></header>
<div class="row">
<section class="col-sm-12">
<a id="main-content"></a>
<div class="region region-content">
<section id="block-system-main" class="block block-system clearfix">
<div class="teaser-container node node-page" about="/web-design-and-development-terms-and-conditions-web-choice-uk-ltd" typeof="foaf:Document">
<div class="teaser-text zoomIn animated">
<div class="field field-name-body field-type-text-with-summary field-label-hidden">
<div class="field-items text-left">
<div class="field-item even" property="content:encoded">
<p>Please read these Terms and Conditions carefully. All contracts that the Developer may enter into from time to time for the provision of the Developer's services shall be governed by these Terms and Conditions. By engaging the Developer, the Customer agrees to the acceptance of these Terms and Conditions.</p>
<p><strong>TERMS AND CONDITIONS</strong></p>
<p><strong>1.&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; Definitions</strong></p>
<p>1.1&nbsp;&nbsp;&nbsp; In these Terms and Conditions, except to the extent expressly provided otherwise:</p>
<p>"<strong>Assignment Works</strong>" means those elements of the Website such as the visual appearance of the Website (including page layouts, artwork, photographs, logos, graphics, animations, video works and text comprised in the Website, as applicable) together with the source-code, all mark-ups and style sheets comprised in or generated by the Website (excluding any Third Party Materials and the Customer Materials) the rights in which are to be assigned (rather than licensed) by the Developer to the Customer under Clause 6, as specified in Section 3 of the Statement of Work;</p>
<p>“Acceptance Period” means up to 30 day after the Licensed work is provided to the Customer. During these 30 days, The Developer will carry out any tweaks and bug fixes reported by the Customer to ensure the website is working in conformity with Section 2 of the Statement of Works. proposal or quotation agreed with the Customer (This excludes any support hours.)</p>
<p>“Acceptance Period” means a maximum of 30 days after the Assignment Works is provided to the Customer. During these 30 days, the Developer will carry out any tweaks and bug fixes reported by the Customer to ensure the Assignment Works will be in conformance with the Statement of Works, Proposal or Quotation (as applicable) agreed by the Customer.</p>
<p>"<strong>Charges</strong>" means:</p>
<p>(a)&nbsp;&nbsp;&nbsp; the amounts specified in Section 7 of the Statement of Work and elsewhere in these Terms and Conditions.</p>
<p>(b)&nbsp;&nbsp;&nbsp; such other amounts as may be agreed in writing by the parties from time to time; and</p>
<p>(c)&nbsp;&nbsp;&nbsp; amounts calculated by multiplying the standard time-based charging rates of the Developer (as notified by the Developer to the Customer before the date of the Contract) by the time spent by the personnel of the Developer performing the Services (rounded down by the Developer to the nearest quarter hour.</p>
<p>"<strong>Contract</strong>" means a particular contract made under these Terms and Conditions between the Developer and the Customer.</p>
<p>"<strong>Customer</strong>" means the person or entity identified as such in Section 1 of the Statement of Work;</p>
<p>"<strong>Customer Materials</strong>" means all works and materials supplied by or on behalf of the Customer to the Developer for incorporation into or integration with the Website, or for use in connection with the Services.</p>
<p>"<strong>Developer</strong>" means Web Choice UK Ltd, a company incorporated in England and Wales (registration number <em>08904981</em>) having its registered office at 36 Goldcroft, Yeovil, Somerset, BA21 4DH;</p>
<p>"<strong>Developer Credit</strong>" means a textual credit for the Developer incorporating a link to the website of the Developer, in a form agreed by the parties acting reasonably (generally at the footer of the website);</p>
<p>"<strong>Development Services</strong>" means the design and development of the Website by the Developer;</p>
<p>"<strong>Documentation</strong>" means the documentation for the Website produced by the Developer, if any, and delivered or made available by the Developer to the Customer;</p>
<p>"<strong>Effective Date</strong>" means the date of execution of the Contract;</p>
<p>"<strong>Force Majeure Event</strong>" means an event, or a series of related events, that is outside the reasonable control of the party affected (including failures of the internet or any public telecommunications network, hacker attacks, denial of service attacks, virus or other malicious software attacks or infections, power failures, industrial disputes affecting any third party, changes to the law, disasters, epidemics, pandemics, explosions, fires, floods, riots, terrorist attacks and wars);</p>
<p>"<strong>Intellectual Property Rights</strong>" means all intellectual property rights wherever in the world, whether registrable or unregistrable, registered or unregistered, including any application or right of application for such rights (and these "intellectual property rights" include copyright and related rights, database rights, confidential information, trade secrets, know-how, business names, trade names, trade marks, service marks, passing off rights, unfair competition rights, patents, petty patents, utility models, semi-conductor topography rights and rights in designs);</p>
<p>"<strong>Licensed Works</strong>" means the Website excluding the Third Party Materials and the Customer Materials;</p>
<p>"<strong>Services</strong>" means any services that the Developer provides to the Customer, or has an obligation to provide to the Customer, under these Terms and Conditions;</p>
<p>"<strong>Source Code</strong>" means software code in human-readable form, including human-readable code compiled to create software or decompiled from software, but excluding interpreted code;</p>
<p>"<strong>Statement of Work</strong>" means a written statement of work agreed by or on behalf of each of the parties;</p>
<p>"<strong>Term</strong>" means the term of the Contract, commencing in accordance with Clause 2.1 and ending in accordance with Clause 2.2;</p>
<p>"<strong>Terms and Conditions</strong>" means all the documentation containing the provisions of the Contract, namely the main body of these Terms and Conditions and the Statement of Work, including any amendments to that documentation from time to time;</p>
<p>"<strong>Third Party Materials</strong>" means the works and/or materials comprised in the Website excluding the Customer Materials, the Intellectual Property Rights in which are owned by a third party, and which are specified in Section 5 of the Statement of Work or which the parties agree in writing shall be incorporated into the Website;</p>
<p>"<strong>Website</strong>" means the website developed or to be developed by the Developer for the Customer under the Contract, as specified in the Statement of Work, including all the Source Code for that website created by the Developer in the course of providing the Services;</p>
<p>"<strong>Website Defect</strong>" means a material adverse effect on the appearance, operation, functionality, security or performance of the Website, but excluding any defect, error or bug caused by or arising as a result of:</p>
<p>(a)&nbsp;&nbsp;&nbsp; any act or omission of the Customer or any person authorised by the Customer to use the Website;</p>
<p>(b)&nbsp;&nbsp;&nbsp; any use of the Website contrary to the intended use by the Customer or any person authorised by the Customer to use the Website;</p>
<p>(c)&nbsp;&nbsp;&nbsp; a failure of the Customer to perform or observe any of its obligations in these Terms and Conditions; and/or</p>
<p>(d)&nbsp;&nbsp;&nbsp; an incompatibility between the Website and any other system, browser types and versions, network, application, program, hardware or software not specified as compatible in the Website Specification; and</p>
<p>"<strong>Website Specification</strong>" means the specification for the Website set out in Section 2 of the Statement of Work, or in the Quotation or Proposal (as the case may be) as it may be varied by the written agreement of the parties from time to time.</p>
<p><strong>2.&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; Term</strong></p>
<p>2.1&nbsp;&nbsp;&nbsp; The Contract shall come into force upon the Effective Date.</p>
<p>2.2&nbsp;&nbsp;&nbsp; The Contract shall continue in force from the effective date until the end of the Acceptance Period, upon which the Contract shall terminate automatically. The contract can also be terminated in accordance with Clause 12 or any other provision of these Terms and Conditions.</p>
<p>2.3&nbsp;&nbsp;&nbsp; Unless the parties expressly agree otherwise in writing, each Statement of Work shall create a distinct contract under these Terms and Conditions.</p>
<p><strong>3.&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; Development Services</strong></p>
<p>3.1&nbsp;&nbsp;&nbsp; The Developer shall provide the Development Services to the Customer.</p>
<p>3.2&nbsp;&nbsp;&nbsp; The Developer shall use reasonable endeavours to ensure that the Development Services are provided in accordance with the timetable set out in Section 6 of the Statement of Work, and that copies of the Website and any Documentation are delivered to the Customer by means of a secure online sharing hyperlink, in accordance with that timetable.</p>
<p>3.3&nbsp;&nbsp;&nbsp; The Customer acknowledges that a delay in the Customer performing its obligations under these Terms and Conditions may result in a delay in the performance of the Development Services; and subject to Clause 11.1 the Developer will not be liable to the Customer in respect of any failure to meet the Development Services timetable to the extent that that failure arises out of a delay in the Customer performing its obligations under these Terms and Conditions.</p>
<p>3.4&nbsp;&nbsp;&nbsp; The Developer shall keep the Customer reasonably informed of the progress of the Development Services and, in particular, shall inform the Customer of any substantial obstacles or likely delays in the performance of the Development Services.</p>
<p>3.5&nbsp;&nbsp;&nbsp; The Developer shall supply to the Customer a current development version of the Website for the purposes of enabling the Customer to assess the progress of the Development Services and provide feedback to the Developer regarding the Website.</p>
<p>3.6&nbsp;&nbsp;&nbsp; If the Contract terminates (for whatever reason) before the delivery of the completed Website to the Customer, the Developer must within 30 days following such termination deliver to the Customer all work in progress towards the Website.</p>
<p><strong>4.&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; Customer obligations</strong></p>
<p>4.1&nbsp;&nbsp;&nbsp; Save to the extent that the parties have agreed otherwise in writing, the Customer must provide to the Developer, or procure for the Developer, such:</p>
<p>(a)&nbsp;&nbsp;&nbsp; co-operation, support and advice;</p>
<p>(b)&nbsp;&nbsp;&nbsp; information, content, images and documentation; and</p>
<p>(c)&nbsp;&nbsp;&nbsp; governmental, legal and regulatory licences, consents and permits,</p>
<p>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; as are reasonably necessary to enable the Developer to perform its obligations under the Contract.</p>
<p>4.2&nbsp;&nbsp;&nbsp; The Customer must provide to the Developer, or procure for the Developer, such access to the Customer's computer hardware, software, networks and systems as may be reasonably required by the Developer to enable the Developer to perform its obligations under the Contract.</p>
<p><strong>5.&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; Customer Materials</strong></p>
<p>5.1&nbsp;&nbsp;&nbsp; The Customer must supply to the Developer the Customer Materials specified in Section 4 of the Statement of Work, in accordance with any timetable specified in Section 6 of the Statement of Work.</p>
<p>5.2&nbsp;&nbsp;&nbsp; The Customer hereby grants to the Developer a non-exclusive license to copy, reproduce, store, distribute, publish, export, adapt, edit and translate the Customer Materials to the extent reasonably required for the performance of the obligations of the Developer and the exercise of the rights of the Developer under these Terms and Conditions.</p>
<p>5.3&nbsp;&nbsp;&nbsp; The Customer warrants to the Developer that the Customer Materials will not infringe the Intellectual Property Rights or other legal rights of any person and will not breach the provisions of any law, statute or regulation, in any jurisdiction and under any applicable law.</p>
<p><strong>6.&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; Intellectual Property Rights</strong></p>
<p>6.1&nbsp;&nbsp;&nbsp; The Developer hereby assigns to the Customer with full title guarantee all of the Intellectual Property Rights in the Website, whether those Intellectual Property Rights exist on the Effective Date or come into existence during the Term. This assignment is for the full term of the assigned rights, including all extensions, renewals, reversions and revivals, and includes the right to bring proceedings for past infringements of the assigned rights. This assignment shall take effect in respect of a work upon the delivery of that work to the Customer.</p>
<p>6.2&nbsp;&nbsp;&nbsp; Subject to any express written agreement between the parties, the Developer shall ensure that the Third Party Materials are:</p>
<p>(a)&nbsp;&nbsp;&nbsp; licensed to the Customer in accordance with the relevant licensor's standard licensing terms (which the Customer acknowledges may be open source or <em>Creative Commons</em> licensing terms);</p>
<p>(b)&nbsp;&nbsp;&nbsp; licensed to the Customer on reasonable terms notified by the Developer to the Customer;</p>
<p>(c)&nbsp;&nbsp;&nbsp; sub-licensed by the Developer to the Customer on reasonable terms notified in writing by the Developer to the Customer; or</p>
<p>6.3&nbsp;&nbsp;&nbsp; To the maximum extent permitted by applicable law:</p>
<p>(a)&nbsp;&nbsp;&nbsp; the Developer irrevocably and unconditionally waives all moral rights (including rights of paternity and rights of integrity) in respect of the Website to which the Developer may at any time be titled; and</p>
<p>(b)&nbsp;&nbsp;&nbsp; the Developer undertakes to ensure that all individuals involved in the preparation of the Website will irrevocably and unconditionally waive all moral rights (including rights of paternity and rights of integrity) in respect of the Website to which they may at any time be entitled.</p>
<p>6.4&nbsp;&nbsp;&nbsp; The Developer must use reasonable endeavors to:</p>
<p>(a)&nbsp;&nbsp;&nbsp; do or procure the doing of all acts; and</p>
<p>(b)&nbsp;&nbsp;&nbsp; execute or procure the execution of all documents,</p>
<p>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; that the Customer may reasonably request from time to time in order to perfect or confirm the Customer's ownership of the rights assigned by these Terms and Conditions.</p>
<p><strong>7.&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; Developer Credit</strong></p>
<p>7.1&nbsp;&nbsp;&nbsp; The Developer may include the Developer Credit on each page of the Website footer in the form of a link pointing to the Developer’s website.</p>
<p>7.2&nbsp;&nbsp;&nbsp; The Customer must retain the Developer Credit on the Website and any adapted version of the Website, must not interfere with the Developer Credit in any way which will have or may reasonably be expected to have a negative impact upon the value of the Developer Credit to the Developer, and may only remove the Developer Credit at the Developer's request.</p>
<p><strong>8.&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; Charges</strong></p>
<p>8.1&nbsp;&nbsp;&nbsp; The Customer shall pay the Charges to the Developer in accordance with these Terms and Conditions.</p>
<p>8.2&nbsp;&nbsp;&nbsp; If the Charges are based in whole or part upon the time spent by the Developer performing the Services, the Developer must obtain the Customer's written consent before performing Services that result in any estimate of time-based Charges given to the Customer being exceeded or any budget for time-based Charges agreed by the parties being exceeded; and unless the Customer agrees otherwise in writing, the Customer shall not be liable to pay to the Developer any Charges in respect of Services performed in breach of this Clause 8.2.</p>
<p>8.3&nbsp;&nbsp;&nbsp; All amounts stated in or in relation to these Terms and Conditions are, unless the context requires otherwise, stated exclusive of any applicable value added taxes, which will be added to those amounts and payable by the Customer to the Developer.</p>
<p>8.4&nbsp;&nbsp;&nbsp; The Developer may elect to vary any element of the Charges by giving to the Customer written notice of variation in the relevant element of the Charges after discussing with, and agreeing by the Customer.</p>
<p><strong>9.&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; Payments</strong></p>
<p>9.1&nbsp;&nbsp;&nbsp; The Developer shall issue invoices for the Charges to the Customer from time to time during the Term as agreed between the Developer and the Customer.</p>
<p>9.2&nbsp;&nbsp;&nbsp; The Customer must pay the Charges to the Developer within the period of the receipt of an invoice issued in accordance with this Clause 9.</p>
<p>9.3&nbsp;&nbsp;&nbsp; The Customer must pay the Charges by debit card, credit card, direct debit, bank transfer or cheque using such payment details as are notified by the Developer to the Customer from time to time.</p>
<p>9.4&nbsp;&nbsp;&nbsp; If the Customer does not pay any amount properly due to the Developer under these Terms and Conditions, the Developer may:</p>
<p>(a)&nbsp;&nbsp;&nbsp; charge the Customer interest on the overdue amount at the rate of 8% per annum above the Bank of England base rate from time to time (which interest will accrue daily until the date of actual payment and be compounded at the end of each calendar month; or</p>
<p>(b)&nbsp;&nbsp;&nbsp; claim interest and statutory compensation from the Customer pursuant to the Late Payment of Commercial Debts (Interest) Act 1998.</p>
<p><strong>10.&nbsp;&nbsp;&nbsp;&nbsp; Warranties</strong></p>
<p>10.1&nbsp; The Developer shall provide the Services with reasonable skill and care.</p>
<p>10.2&nbsp; The Developer warrants to the Customer that:</p>
<p>(a)&nbsp;&nbsp;&nbsp; the Developer has the legal right and authority to enter into the Contract and to perform its obligations under these Terms and Conditions;</p>
<p>(b)&nbsp;&nbsp;&nbsp; the Developer will comply with all applicable legal and regulatory requirements applying to the exercise of the Developer's rights and the fulfilment of the Developer's obligations under these Terms and Conditions; and</p>
<p>(c)&nbsp;&nbsp;&nbsp; the Developer has or has access to all necessary know-how, expertise and experience to perform its obligations under these Terms and Conditions.</p>
<p>10.3&nbsp; The Developer warrants to the Customer that:</p>
<p>(a)&nbsp;&nbsp;&nbsp; the Website as provided will conform in all material respects with the Website Specification.</p>
<p>(b)&nbsp;&nbsp;&nbsp; the Website will be supplied free from Website Defects.</p>
<p>(c)&nbsp;&nbsp;&nbsp; the Website shall incorporate security features reflecting the requirements of good industry practice.</p>
<p>10.4&nbsp; The Developer warrants to the Customer that the Website, when used by the Customer in accordance with these Terms and Conditions, will not breach any laws, statutes or regulations applicable under English law; providing however that the Developer shall have no liabilities under this Clause 10.4 in respect of any such breach caused by the Customer Materials or the Third Party Materials.</p>
<p>10.5&nbsp; The Developer warrants to the Customer that the Website, when used by the Customer in accordance with these Terms and Conditions, will not infringe the Intellectual Property Rights of any person in any jurisdiction and under any applicable law; providing however that the Developer shall have no liabilities under this Clause 10.5 in respect of any such infringement caused by the Customer Materials or the Third Party Materials.</p>
<p>10.6&nbsp; If the Developer reasonably determines, or any third party alleges, that the use of the Website by the Customer in accordance with these Terms and Conditions infringes any person's Intellectual Property Rights, the Developer may acting reasonably to:</p>
<p>(a)&nbsp;&nbsp;&nbsp; modify the Website in such a way that it no longer infringes the relevant Intellectual Property Rights, providing that any such modification must not introduce any Website Defects into the Website and must not result in the Website failing to conform with the Website Specification; or</p>
<p>(b)&nbsp;&nbsp;&nbsp; procure for the Customer the right to use the Website in accordance with these Terms and Conditions.</p>
<p>10.7&nbsp; If the situation in clause 10.6 above is a result of the Customer Materials, the Customer agrees to pay the Developer any relevant charges applicable.&nbsp;</p>
<p>10.8&nbsp; The Customer warrants to the Developer that it has the legal right and authority to enter into the Contract and to perform its obligations under these Terms and Conditions.</p>
<p>10.9&nbsp; All of the parties' warranties and representations in respect of the subject matter of the Contract are expressly set out in these Terms and Conditions. To the maximum extent permitted by applicable law, no other warranties or representations concerning the subject matter of the Contract will be implied into the Contract or any related contract.</p>
<p><strong>11.&nbsp;&nbsp;&nbsp;&nbsp; Limitations and exclusions of liability</strong></p>
<p>11.1&nbsp; Nothing in these Terms and Conditions will:</p>
<p>(a)&nbsp;&nbsp;&nbsp; limit or exclude any liability for death or personal injury resulting from negligence.</p>
<p>(b)&nbsp;&nbsp;&nbsp; limit or exclude any liability for fraud or fraudulent misrepresentation.</p>
<p>(c)&nbsp;&nbsp;&nbsp; limit any liabilities in any way that is not permitted under applicable law; or</p>
<p>(d)&nbsp;&nbsp;&nbsp; exclude any liabilities that may not be excluded under applicable law.</p>
<p>11.2&nbsp; The limitations and exclusions of liability set out in this Clause 11 and elsewhere in these Terms and Conditions:</p>
<p>(a)&nbsp;&nbsp;&nbsp; are subject to Clause 11.1; and</p>
<p>(b)&nbsp;&nbsp;&nbsp; govern all liabilities arising under these Terms and Conditions or relating to the subject matter of these Terms and Conditions, including liabilities arising in contract, in tort (including negligence) and for breach of statutory duty, except to the extent expressly provided otherwise in these Terms and Conditions.</p>
<p>11.3&nbsp; The Developer shall not be liable to the Customer in respect of any losses arising out of a Force Majeure Event.</p>
<p>11.4&nbsp; The Developer shall not be liable to the Customer in respect of any loss of profits or anticipated savings.</p>
<p>11.5&nbsp; The Developer shall not be liable to the Customer in respect of any loss of revenue or income.</p>
<p>11.6&nbsp; The Developer shall not be liable to the Customer in respect of any loss of use or production.</p>
<p>11.7&nbsp; The Developer shall not be liable to the Customer in respect of any loss of business, contracts or opportunities.</p>
<p>11.8&nbsp; The Developer shall not be liable to the Customer in respect of any loss or corruption of any data or database.</p>
<p>11.9&nbsp; The Developer shall not be liable to the Customer in respect of any special, indirect or consequential loss or damage.</p>
<p>11.10 The liability of the Developer to the Customer under the Contract in respect of any event or series of related events shall not exceed the greater of the total amount paid and payable by the Customer to the Developer under the Contract in the 12-month period preceding the commencement of the event or events.</p>
<p>11.11 The aggregate liability of the Developer to the Customer under the Contract shall not exceed the greater of the total amount paid and payable by the Customer to the Developer under the Contract.</p>
<p><strong>12.&nbsp;&nbsp;&nbsp;&nbsp; Termination</strong></p>
<p>12.1&nbsp; Unless otherwise agreed by both parties, the Contract will automatically terminate at the end of the Acceptance Period as per Clause 2.2</p>
<p>12.2&nbsp; The Customer may terminate the Contract by giving to the Developer written notice of termination.</p>
<p>12.3&nbsp; Either party may terminate the Contract immediately by giving written notice of termination to the other party if:</p>
<p>(a)&nbsp;&nbsp;&nbsp; the other party commits any breach of the Contract, and the breach is not remediable;</p>
<p>(b)&nbsp;&nbsp;&nbsp; the other party commits a breach of the Contract, and the breach is remediable but the other party fails to remedy the breach within the period of 30 days following the giving of a written notice to the other party requiring the breach to be remedied; or</p>
<p>12.4&nbsp; Subject to applicable law, either party may terminate the Contract immediately by giving written notice of termination to the other party if:</p>
<p>(a)&nbsp;&nbsp;&nbsp; the other party:</p>
<p>(i) &nbsp;&nbsp;&nbsp; is dissolved;</p>
<p>(ii)&nbsp;&nbsp;&nbsp; ceases to conduct all of its business;</p>
<p>(iii)&nbsp;&nbsp; is or becomes unable to pay its debts as they fall due;</p>
<p>(iv)&nbsp;&nbsp; is or becomes insolvent or is declared insolvent; or</p>
<p>(v)&nbsp;&nbsp;&nbsp; convenes a meeting or makes or proposes to make any arrangement or composition with its creditors;</p>
<p>(b)&nbsp;&nbsp;&nbsp; an administrator, administrative receiver, liquidator, receiver, trustee, manager or similar is appointed over any of the assets of the other party;</p>
<p>(c)&nbsp;&nbsp;&nbsp; an order is made for the winding up of the other party, or the other party passes a resolution for its winding up (other than for the purpose of a solvent company reorganisation where the resulting entity will assume all the obligations of the other party under the Contract); or</p>
<p>(d)&nbsp;&nbsp;&nbsp; if that other party is an individual:</p>
<p>(i) &nbsp;&nbsp;&nbsp; that other party dies;</p>
<p>(ii)&nbsp;&nbsp;&nbsp; as a result of illness or incapacity, that other party becomes incapable of managing his or her own affairs; or</p>
<p>(iii)&nbsp;&nbsp; that other party is the subject of a bankruptcy petition or order.</p>
<p>12.5&nbsp; The Developer may terminate the Contract immediately by giving written notice to the Customer if:</p>
<p>(a)&nbsp;&nbsp;&nbsp; any amount due to be paid by the Customer to the Developer under the Contract is unpaid by the due date and remains unpaid upon the date that that written notice of termination is given; and</p>
<p>(b)&nbsp;&nbsp;&nbsp; the Developer has given to the Customer at least 30 days' written notice, following the failure to pay, of its intention to terminate the Contract in accordance with this Clause 12.5.</p>
<p><strong>13.&nbsp;&nbsp;&nbsp;&nbsp; Effects of termination</strong></p>
<p>13.1&nbsp; Upon the termination of the Contract, all of the provisions of these Terms and Conditions shall cease to have effect, save that the following provisions of these Terms and Conditions shall survive and continue to have effect (in accordance with their express terms or otherwise indefinitely: Clauses 1, 3.7, 6.1, 6.4, 7, 9.2, 9.4, 11, 13, 15 and 16.</p>
<p>13.2&nbsp; Except to the extent expressly provided otherwise in these Terms and Conditions, the termination of the Contract shall not affect the accrued rights of either party.</p>
<p>13.3&nbsp; Within 30 days following the termination of the Contract for any reason:</p>
<p>(a)&nbsp;&nbsp;&nbsp; the Customer must pay to the Developer any Charges in respect of Services provided to the Customer before the termination of the Contract; and</p>
<p>(b)&nbsp;&nbsp;&nbsp; the Developer must refund to the Customer any Charges paid by the Customer to the Developer in respect of Services that were to be provided to the Customer after the termination of the Contract,</p>
<p>&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; without prejudice to the parties' other legal rights.</p>
<p><strong>14.&nbsp;&nbsp;&nbsp;&nbsp; Subcontracting</strong></p>
<p>14.1&nbsp; Subject to any express restrictions elsewhere in these Terms and Conditions, the Developer may subcontract any of its obligations under the Contract.</p>
<p>14.2&nbsp; The Developer shall remain responsible to the Customer for the performance of any subcontractor obligations.</p>
<p><strong>15.&nbsp;&nbsp;&nbsp;&nbsp; General</strong></p>
<p>15.1&nbsp; No breach of any provision of the Contract shall be waived except with the express written consent of the party not in breach.</p>
<p>15.2&nbsp; If any provision of the Contract is determined by any court or other competent authority to be unlawful and/or unenforceable, the other provisions of the Contract will continue in effect. If any unlawful and/or unenforceable provision would be lawful or enforceable if part of it were deleted, that part will be deemed to be deleted, and the rest of the provision will continue in effect (unless that would contradict the clear intention of the parties, in which case the entirety of the relevant provision will be deemed to be deleted).</p>
<p>15.3&nbsp; The Contract may not be varied except by a written document signed by or on behalf of each of the parties.</p>
<p>15.4&nbsp; Neither party may without the prior written consent of the other party assign, transfer, charge, license or otherwise deal in or dispose of any contractual rights or obligations under these Terms and Conditions.</p>
<p>15.5&nbsp; The Contract is made for the benefit of the parties, and is not intended to benefit any third party or be enforceable by any third party. The rights of the parties to terminate, rescind, or agree any amendment, waiver, variation or settlement under or relating to the Contract are not subject to the consent of any third party.</p>
<p>15.6&nbsp; Subject to Clause 11.1, these Terms and Conditions shall constitute the entire agreement between the parties in relation to the subject matter of these Terms and Conditions, and shall supersede all previous agreements, arrangements and understandings between the parties in respect of that subject matter.</p>
<p>15.7&nbsp; The Contract shall be governed by and construed in accordance with English law.</p>
<p>15.8&nbsp; The courts of England shall have exclusive jurisdiction to adjudicate any dispute arising under or in connection with the Contract.</p>
<p><strong>16.&nbsp;&nbsp;&nbsp;&nbsp; Interpretation</strong></p>
<p>16.1&nbsp; In these Terms and Conditions, a reference to a statute or statutory provision includes a reference to:</p>
<p>(a)&nbsp;&nbsp;&nbsp; that statute or statutory provision as modified, consolidated and/or re-enacted from time to time; and</p>
<p>(b)&nbsp;&nbsp;&nbsp; any subordinate legislation made under that statute or statutory provision.</p>
<p>16.2&nbsp; The Clause headings do not affect the interpretation of these Terms and Conditions.</p>
<p>16.3&nbsp; References in these Terms and Conditions to "calendar months" are to [the 12 named periods (January, February and so on) into which a year is divided.</p>
<p>16.4&nbsp; In these Terms and Conditions, general words shall not be given a restrictive interpretation by reason of being preceded or followed by words indicating a particular class of acts, matters or things.</p>
</div>
</div>
</div>
</div>
</div>
</section>
</div>
</section>
</div>
</div>
</div>
<div class="content_bottom"><div class="container"> <div class="region region-content-bottom">
<section id="block-block-11" class="block block-block project-started clearfix">
<h2 class=" zoomIn animated">Let's Get Your<br>
Project Started</h2>
<p>We will help you to achieve your goals and to grow your business.</p>
<p><a class="button" href="contact.php">Request A Quote</a></p>
</section>
</div>
</div>
</div>

<?php include 'include/footer.php'; ?>

<script type='application/ld+json'> 
{
  "@context": "http://www.schema.org",
  "@type": "WebSite",
  "name": "Web Choice UK",
  "alternateName": "SEO Company, Web Design in UK, London",
  "url": "https://www.webdesignchoice.co.uk/"
}
 </script>
<script type='application/ld+json'> 
{
  "@context": "http://www.schema.org",
  "@type": "Organization",
  "name": "Web Choice UK",
  "url": "https://www.webdesignchoice.co.uk/",
  "logo": "https://www.webdesignchoice.co.uk/img/logo.webp",
  "description": "Web Choice UK is an award-winning web development and digital marketing company - Giving outstanding results through branding, web design, web development and result oriented SEO and online marketing.",
  "address": {
    "@type": "PostalAddress",
    "streetAddress": "36 Goldcroft",
    "addressLocality": "Yeovil",
    "addressRegion": "England ",
    "postalCode": " BA21 4DH",
    "addressCountry": "United Kingdom"
  },
  "contactPoint": {
    "@type": "ContactPoint",
    "telephone": "+44 1935 507879",
    "contactType": "info@webchoiceuk.com"
  }
}
 </script>
<script type='application/ld+json'> 
{
  "@context": "http://www.schema.org",
  "@type": "ProfessionalService",
  "name": "Web Choice UK",
  "url": "https://www.webdesignchoice.co.uk/",
  "logo": "https://www.webdesignchoice.co.uk/img/logo.webp",
  "image": "https://media-exp1.licdn.com/dms/image/C561BAQGHqRYopxhIYQ/company-background_10000/0/1551823147891?e=1639753200&v=beta&t=mcr9--KFd-u3iHxMpDngoMmq0hhRb_TM_phOapIdM18",
  "description": "Web Choice UK is an award-winning web development and digital marketing company - Giving outstanding results through branding, web design, web development and result oriented SEO and online marketing.",
  "address": {
    "@type": "PostalAddress",
    "streetAddress": "36 Goldcroft, Yeovil BA21 4DH, United Kingdom",
    "addressLocality": "Yeovil",
    "addressRegion": "England",
    "postalCode": "BA21 4D",
    "addressCountry": "United Kingdom"
  },
  "geo": {
    "@type": "GeoCoordinates",
    "latitude": "50.945709",
    "longitude": "-2.628690"
  },
  "hasMap": "https://goo.gl/maps/ft1zd18g6i1mPxhB7",
  "contactPoint": {
    "@type": "ContactPoint",
    "telephone": "01935507879",
    "contactType": "info@webchoiceuk.com"
  }
}
 </script>
<div class="navbar-header custom-header">
<div class="container">
<div class="ch-logo"><a class="logo navbar-btn pull-left" href="index.php" title="Home">
<img src="data:image/webp;base64,UklGRvYFAABXRUJQVlA4TOoFAAAvOQAOEBEyaRvIu/pXPBER/U8ZuWoiEEjyZ11jh4Ef8P6nEBBAjEKQbbP6Y/8QEZGNPNiRZMdtOv+YfAFZ6Xwf3AcBjsBBJEmKlK3vmO913stbQNC2bVz+bL6D6dBMErVtZx7dyY/atm3b7crtqmPbNurd2LZt21zZWNlIMpkvE8CgbRtB5k977X73CCKk0bZt6s3Kp9i2bdu27dR2/8Wpbdu2G9S2bRtxxssEQAJbv4YJKgaSsorQajyJTYVcjupBD9WJQhWfite688UavAP/9Gec1KJFVHx/H9BDhh2CUITZeFvyq+Tgm9T/8Du+oaLl9/uAjXBAHe6/eP+shp4aQ/v/jf329x/Abnhj+aPet0fV/8SYGzXmPsZauICDcMHae/X43hK1bSwdh8eIAYcRg8e3Ytymse0ZzIMM1qFBgYr/sIENjCUAGfNu1RlUbpjnWse2T1ABVvEZZ7EPR6EBAKBChYx0LMYjiA4AVFQ8KZKgfTLPWvEG0aCHjhMYjR9gEfcxGvFwQAu+dADReCMJgbY2z8p4CF/QwsBODAIfQ8FceGAQfjUAvnhYXTTEEq4gArR4jSqwF2vggq0NQASuIH9lPtuCPNBiE+aA3RDoiRqoCSCPtGBON59mYBbIMDAUfcBBHEUcfiSAWZVk4G6DQ5ASDPTESnAUrxCBHwkSDiEgzadz4Q8yxmMbOIxPSIQaAPyr3VzMvczfmjEVZHzBA3Ac79CUAKZKzNABAGiHTQN3nMJjOJ6Co74n2KANAAAwElwh0A4beOEYYvDwGFTiRwAYBQCYvzbAIWAWZkHDJ1RjN4Kw5BkBExIcigYAMB1coaMTAADQjJ8YTHTC2FKOHhvmQwDW4FMAmA4AUgM+gysEFsJiTCOy3DuvVQeGzgMcLBDqQwBYlpAK5q+FsAT8CABtEIY1lwxhwlyDjcNSACAz18iELogAS0kh+oEIc4KGZ6wKU34AoHAwG2DmbYKC5wGgH9ITHBLAeWKRiTEmydAqcmhGxdmEdAQmuDQ4DMnJTb3Dl2GyCk6Au7Y27E0IhEuCDewTzsEg1URDjwH6AO0SB4ErExFafUHH1QQXmBNA3wRFDzUNfgkAAJuoypRMxa0BOKkNWyjQA8yQGjQl4J4Wc6g6LwgAdNnvKI7xL0ACLZIbPqJNlETkJBmeQoQWN1CDqQ2JVKvNIlC2+g3MCcYF31GAo1gHAEAG5uEmvupx0ACOvuhSQPQDGNAvmA8BAACIwB2MQxZ0FzRxJ2FsOanSb/z98rTAE6YA3Z9hGaYXxoghoitUtbuA6ZD9hb6TxnqKKg7RH+8B6Pc1wELNyL7o5RQ4WCiZBkDJIFd80qUQXU7y3k0A5LBnaJwj3pEyCh67YY9fBIJ2K3mrkYalwOSmdQDAs1BTaYfnunw0VxJNHRQpDNhARZMnfnprIz1NWLJkkKxzXi8ACcUva+Ux9cEuA6hTsRDiA/Sp5kiHuXI/sTUVUa/zcBuAoKLRRCbkWcuz1l84DaHpkILs5DZgKgCORZ05PiC6AWZn5pMmUwH7tQOMShVpoWbQuGJsEKJ2+wFYBFCk0ripd843ghajeMLnKyeJkkUAoFo3YFLx3R01gklcN0+oVXDoyHxOiLpVD32mA4YUW62RQUaTn/FuKtVl141Ko5FN1zegzgfQNzkZbaAD+gAiVylqxKksq8klH9QhS9cP00SHyM5rzs6aemKE3USI+qWjuqERRE6ZTRTIlLruMVPbhOPSTovJIWt0o0GtSyBngi4PtLnkhXbdNvLyiI8iHArxWS6qS2qxFeIFQMpJuABWlAB/THcD39m54Bx9VC+EYE3g5DM6DQul2qbO1xWRwUYTY+mzKHzUw9zTBtBQqI7YTRedc8tP0GEqVIBAxlh7Khaf9bDXvABAm5cgoTxp4VCz4bgUYzxhc00w0V3cmsfBk1eeSMe5ZxwM8If6A3+MdwEvraWhUD29I1/V2obXlqtlpF405U/aNav1EX90W61mWgaKZEGHPBEAgm7fvdZqtZ84BQ==" alt="Home" style="width:52px; height: 52px;">
</a>
</div>
<div class="call-email"><a href="tel:01935507879" class="calluslogo"><img src="data:image/webp;base64,UklGRmwFAABXRUJQVlA4TF8FAAAvMkAMEBEyaRvat/OveCIi+p+Vl8MxGXixYDKE/Ek7FaRtwKLs9D8AcAwAA4AAUmxrW7Zl4+7u7m7JYXg0EpVE4k9YYgb/jzXr7u4X8rzv87zfCKRg27bsyTl3ae7uvv1vm8UNb0scRKe5u7tWh+heOehEiyQn+kO3trZlW7TPg7u7u7sTEhJTAV04RE4JznhGA+M+04NF7u6fHNq2Te2ZvxXbto3SflVsW5Vt20llO+l+lrFt28lvOpAkNW5E4VwdG1wR+QNCoCHGM69UjjowWkV1RdVilIriKCRGavSD8SZ6Gt0QIwXvYXhMZF6sQiOigdQgBhJJDCTCgBJU5/8FYjyKjtNBvB327Hbm+aY0P+pDoRECQABIAMUF0ADLGPnRmWgl7rY/u5N5WobWRcMpBKFAACKC4glEACJAEIp+dJsOJpqFb415Nz3pl2gfFUMIEAIBAEAABMoHCAhCMIKeRuNxquXZ3fQ4EltoUiJAOvV1SoQAgBTtohhOMvZEM5BdzXvpUaHoDHWNkAgE5XkjnRJFeq5BMBGXoj5IreS99DAW8VH7bgk1CdC9Q+hK8dQZ6b15Lz2MxCW0BxAU2SABCAj+t4v2uBj17P0QW6hj0QG0ym7H6IStmNST99KDAZhUVjZAlqcJMDHGQBzv5P30oAL2AAAZKDudYDc17Cysp2IAMFwWraMY1pfF3U/3W2AQAIxCFmUJgz5Z0aI4ExaFECCjkQAACMEiAID76X41CgBGJSFCIhR8srI6AGAIQqEm5w4OOy7fMCmfskQx1CUAIJRG/V/dZqF8PrUy28/dMH9s2Lh1imYJABAGANxP9yujPtTkjms3TSkaYNn8VHP70iwFAKjz8f/qGoCOEFTk5kM3zWqaAgA27rtucsHQKgEA0AHQitTk4rmpAADmNEwzveE/zZIAoBmgDtTkw9efA4Afv/4ztu81zz/+qFkCAdQF1OxvFgg8fvQFALh1+WPfHyw1L5ZolwFBDUDpqvzyarbPP/8EsK19u025e00yRbsEQDFAkZqEdTnb3Tz+HoAtS5aZXjUMkUCFoSrJJEOeLfPk3bcANu2ZGCIBAP+guuPW5+50ZcMZAIvGplmxfBggAamA7z3Nduva9/2MSxsOA9i8LUtm0i4h/Aa8rO44EZidNd/CN7tdPfEWgO1Hr1u9OAERmFYx7D1/0aa1/2mQgFcQnrXsuFU5m729O8e1U28D2LiJgzevWrWKJVMcvH7BojSxbvW/jt07bMHIfFVJ8BRwo36PCMC23MNe35pjbP9rAOZ0smXL/3aduGJmTQBmt8x28No+O/duVZW4A0humzfb8o74dn+Fi2v2e//5d912PhX/otYJUArgPR73Nlu+CgA25W6w5u0sF5Y8cm7jeccXzwEASExc3vGysc3PVCQT4TkA4EjjvFmas9Spf6fdPf7MpyaOLT9rezpmQdUyT9594vzye34+nTiWf1pN4gQA0JGQ3zhvpmZNdyD/gA//f/Xg/Kue//vGl/jL/OyF9nzaZ33ORjVJ+Uz2AwDe0KXmeTMve4E9eXvFQCJzs+eDmsSl4qtYTgUDp21FogDLi4WbONYgof031y0RM4U/VTlgx+EPZnYWPmHSCKZtJzAJn7oV4Dj2jGbaEsBeHO+rOpqB5NFISsb0vgRkI8DlUUhcDkHljx3p6Ir44RLx6Ip0qARSKcDeoRJ7ESAVqoFsTER/+jNERn9oACYiG1oCp1AXB6OCVkkFdBB1cRIaA98wAi1wKkafKLRBUj6dQguMwDcYEqiORfS4IicBT+gok8MwNPAOy9EAVTESOykBz/EbOSGHfuM5EmgnRiKloTIAAA==" style="width:46px; height: 45px;" alt="Home"></a> <a href="contact.php" class="emailuslogo"><img src="data:image/webp;base64,UklGRtwFAABXRUJQVlA4TNAFAAAvM0AMEBEyadsQy9tF9D/UDfVpE4JAkAD2Z5xggx0EAimOYICHv/9ZACDZ8RSBQNL+2EtERLocoNa27VqZ35NBM1D0b+nh/0/QtIDHbcK954YKHEWSZCsZ8U7vqfkz7Qc36MAjJ6KhRrKt2urZATz9JEOMnMjXpH5EX/0sWA5t26b2zN9WbNtGab8qtq3Ktu10tvO6n2Vs27adMHDbNk6MHtuExtn9Brja9p9fnn9us21jtK0DaHMdUk08AtuavDW5plb7E36/z6dDgLtt2/Hl+tlWtt3kzfoL7M22a7LtpqY2jk3Nb1uNbZzdC0W2bdXRPveGwdE4EpsZRaFj1DynVFxr8szcn0Jh27YNultl9wpEwIyO81YyasY0iCprZWIKREkUEfMlesM8iG5GZ3Ty8Bg26DTPpahf1J2qxSCRdJAIA/mo0n+CmGvRHtqGh4uz8zxq09SoE0VGCMD/VgBNAlTDHOZfdDCaj4sLs9e5F3qdxxacpwhEAgGIKM0EIgARIIhEFzpP29Im4NVse8utC26iHyKAEAgAAAIg0A4QEESgH92MhmL/1Owt19i3XDdgH9KBdAY7jxAAkKZgpGMfsykah1/j9p5rMkIaESERCNp1I51HTZGDYDjCqBO+jNp7LonIROvewogE6E8SWlMmtcS3ur3nEosQTQGUpk2QAASUCABBUxyL2tcHsYqaB83eWbKvGS2wGiOq9p5zN4xorK2Q7TIBhsd0x56+feRSDJsAgCySXSnYSHPxrAsspXQAWCeBEACkYyrGt+4+cq6HHgCwg2xsqR7RTZxrEmBGiACyhwQAQASmYw4AwEfOZSgA2EVChAQHAlzBfQBAL0RCRQoGEhwkmMgUSDAwwRwGBLdIAABE0gD4DyBQSDCw341IBwn+a8VhwCAdLXQDgI88lURVKMnfqARH2i/qWES64CAHgZRCIgWASjHlANAcgoq8fJYSBr79A2PAaBViViGmlWJSJUZVYlh8sw7JvdVTgGYAaECgOk8P75PJySCjnJI691LJ2gDyr91djVQ0ohsu3KQgAoA6fwCU5O2+9PWtk53U4V3QMTOIipUx7h5tuLzh/VEdvDlHZLzp1URlAJQHMvB2/5SaHN1EZ8Q1LfLWSPHi81er88l0W6tz/qZk6Mlbn6hkQFAOAAVrEgAAkD+dnmU3L4L2iU5Culw+3D7YUFEzzFDvvToFJX4AgEoCIB0AqSXZ1fD0nJqoPsblhY3d+BkBAOD9U8uL6bPLUtf+ZVHLk0cNAABGCigFoCY77W1ZnKb8bv9fPA6aBkjPBTi/t7nZbENFJuAnv38euVxRyEb4BPUDCAAAsL5GmD5X0PwPvLyklqeyr4bAWyN5zbdOtwP9IiDMU16cFgAAgPGh8QUArwmMtLpEpCWf3xQAAADc3OY/fzyp7AcAgPzml7jAytyEnDuFhPAeAHdHDyCwspDEunI5dYHueV7jc1JYZXbMLBJwDyDcGpHL80mcJ59TGwBGy61/TomqzozI8IPgJgDODMjluSTBL5dVHQJmy6l7TIuvTA25SHQSFwCQW5Mvn3dJgbnMygj4R8uufspMrkwOuEoC5QHgMa5XrsjX98P3/8vn75OGRAJCSIRAJEJIwABN5HFdu1gWnta9njwI/8JtAADsLMnnbSWGJsKI/G3FIGlikBikTRBhABTmsBcAgHaGf3veQb3oH/9bAADwgMIN76CSRNguh7n0f/01XJWC/5jbBs5i94bXcHH38b8bOmG8+rDhNdyR+ID5feAZRuwjy+8R9mDTLhKbsacKiMYhdw9JuRhbNsAvBDi+g8TxEIy+/viG1shcJ5FJnfANRsIXCrB5lcTmaOzEPwbgF4ajK31YIaMPNAz7YE7Yj8rYFv2fJek/bY/GT/8zAV6hH+rRlJhOUeQESf/oYLQAF2BJ6IqymEHXRyRuMLuibXgIq8IjzEU1lEZ/rKcs3MZ7/A6/6T1uI4vWR6cpD4/GzgA=" alt="Home" style="width:46px; height: 44px;"></a></div>
<div class="ch-menu">
<a class="btn-navbar navbar-toggle">
<div class="hamburger hamburger--elastic js-hamburger">
<div class="hamburger-box">
<div class="hamburger-inner"></div>
</div>
</div>
</a>
</div>
</div>
</div>
<script src="../cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="../cdn.jsdelivr.net/npm/bootstrap%403.3.7/dist/js/bootstrap.min.js" type="text/psajs" data-pagespeed-orig-index="8"></script>
<script>jQuery(".navbar-toggle").click(function(){if(jQuery('.hamburger').hasClass('is-active')){setTimeout(function(){jQuery('.navsmallhead').removeClass('in');jQuery(".hamburger").removeClass("is-active");},300);}else{setTimeout(function(){jQuery('.navsmallhead').addClass('in');jQuery(".hamburger").addClass("is-active");},300);}});jQuery('.btn-readmore').click(function(){if(jQuery('.design_tg').is(':visible')){jQuery('.btn-readmore').php('Show More');jQuery(".design_tg").slideUp()}else{jQuery('.btn-readmore').php('Show Less');jQuery(".design_tg").slideDown()};return false});jQuery(".navbar-nav > li > a .caret").click(function(){jQuery(this).parent().next().slideToggle("slow");return false});jQuery(".dropdown-menu > li.dropdown-submenu a .caret").click(function(){jQuery(this).parent().next().slideToggle("slow");return false});jQuery(document).ready(function(){jQuery('.accordion-header').toggleClass('inactive-header');jQuery('.accordion-header').first().toggleClass('active-header').toggleClass('inactive-header');jQuery('.accordion-content').first().slideDown().toggleClass('open-content');jQuery('.accordion-header').click(function(){if(jQuery(this).is('.inactive-header')){jQuery('.active-header').toggleClass('active-header').toggleClass('inactive-header').next().slideToggle().toggleClass('open-content');jQuery(this).toggleClass('active-header').toggleClass('inactive-header');jQuery(this).next().slideToggle().toggleClass('open-content')}else{jQuery(this).toggleClass('active-header').toggleClass('inactive-header');jQuery(this).next().slideToggle().toggleClass('open-content')}});return false});;</script>
<script src="../cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>
<script>$(document).ready(function(){var windowsize=$(window).width();if(windowsize>1024){$('.views-bx-slideshow3').bxSlider({auto:false,speed:500,pause:5000,mode:'horizontal',autoControls:false,pager:false,controls:true,captions:false,minSlides:1,maxSlides:1,moveSlides:1,slideWidth:2000,slideMargin:20,touchEnabled:true,});}else if(windowsize>767){$('.views-bx-slideshow3').bxSlider({auto:false,speed:500,pause:5000,mode:'horizontal',autoControls:false,pager:false,controls:true,captions:false,minSlides:1,maxSlides:1,moveSlides:1,slideWidth:250,slideMargin:20,touchEnabled:true,});}else{$('.views-bx-slideshow3').bxSlider({auto:false,speed:500,pause:5000,mode:'horizontal',autoControls:false,pager:false,controls:true,captions:false,minSlides:1,maxSlides:1,moveSlides:1,touchEnabled:true,});}});</script>
<script>_linkedin_partner_id="3778121";window._linkedin_data_partner_ids=window._linkedin_data_partner_ids||[];window._linkedin_data_partner_ids.push(_linkedin_partner_id);</script><script>(function(l){if(!l){window.lintrk=function(a,b){window.lintrk.q.push([a,b])};window.lintrk.q=[]}var s=document.getElementsByTagName("script")[0];var b=document.createElement("script");b.type="text/javascript";b.async=true;b.src="../snap.licdn.com/li.lms-analytics/insight.min.js";s.parentNode.insertBefore(b,s);})(window.lintrk);</script>
<noscript>
<img height="1" width="1" style="display:none;" alt="" src="https://px.ads.linkedin.com/collect/?pid=3778121&amp;fmt=gif"/>
</noscript>
</body>



<!-- Mirrored from www.webdesignchoice.co.uk/ by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 24 Jun 2022 16:26:33 GMT -->
</html>